import React, { useEffect, useState, useMemo, useRef, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import api from '../../utils/api';
import toast from 'react-hot-toast';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { APP_CONFIG } from '../../config/app';
import { useAuthStore } from '../../store/useAuthStore';

// ==================== TYPES ====================
interface DailyReportData {
  date: string;
  dayName: string;
  totalSales: number;
  totalInstallments: number;
  totalCollected: number;
  totalPending: number;
  totalCustomers: number;
  cashInHand: number;
  bankDeposit: number;
  recoveryRate: number;
  outstanding: number;
  // Detailed transactions
  transactions: Array<{
    id: string;
    customerName: string;
    customerUrdu?: string;
    fatherName?: string;
    phone: string;
    productName: string;
    productNameUrdu?: string;
    amount: number;
    type: 'sale' | 'installment' | 'advance' | 'recovery';
    status: 'paid' | 'pending' | 'partial';
    date: string;
  }>;
  // Summary breakdowns
  cashSales: number;
  cashSalesReturn: number;
  installmentSales: number;
  installmentCollections: number;
  advancePayments: number;
  fineReceived: number;
  processingFee: number;
  // Account details
  openAccounts: number;
  closedAccounts: number;
  netAccounts: number;
  // Outstanding details
  freshOutstanding: number;
  regularOutstanding: number;
  totalOutstanding: number;
}

// ==================== COMPONENTS ====================

const ReportHeader: React.FC<{ 
  title: string; 
  subtitle?: string; 
  isUrdu: boolean;
  reportDate?: string;
}> = ({ title, subtitle, isUrdu, reportDate }) => {
  const now = new Date();
  const dateStr = reportDate || now.toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const dayName = now.toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK', { weekday: 'long' });

  return (
    <div className="text-center mb-6 pb-4 border-b-2 border-gray-300 dark:border-gray-600">
      <h1 className="text-2xl font-extrabold text-gray-800 dark:text-white tracking-tight">
        {APP_CONFIG.companyName}
      </h1>
      <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
        {isUrdu ? APP_CONFIG.addressUr : APP_CONFIG.address}
      </p>
      <div className="mt-3">
        <h2 className="text-xl font-bold text-blue-700 dark:text-blue-400">{title}</h2>
        {subtitle && <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">{subtitle}</p>}
        <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">
          {isUrdu ? 'رپورٹ کی تاریخ' : 'Report Date'}: {dateStr} ({dayName})
        </p>
      </div>
    </div>
  );
};

const ReportFooter: React.FC<{ isUrdu: boolean }> = ({ isUrdu }) => {
  const now = new Date();
  const dateStr = now.toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const user = useAuthStore((s) => s.user);

  return (
    <div className="mt-6 pt-4 border-t-2 border-gray-300 dark:border-gray-600">
      <div className="flex flex-wrap justify-between text-xs text-gray-500 dark:text-gray-400">
        <span>{isUrdu ? 'پرنٹ کی تاریخ' : 'Print Date'}: {dateStr}</span>
        <span>{isUrdu ? 'پرنٹ کا وقت' : 'Print Time'}: {now.toLocaleTimeString()}</span>
        <span>{isUrdu ? 'تیار کردہ' : 'Generated By'}: {user?.displayName || user?.username || '—'}</span>
      </div>
      <div className="text-center text-[10px] text-gray-400 dark:text-gray-500 mt-2">
        {isUrdu ? 'یہ رپورٹ خودکار نظام سے تیار کی گئی ہے' : 'This report is auto-generated by the system'}
      </div>
    </div>
  );
};

const StatusBadge: React.FC<{ status: string; isUrdu: boolean }> = ({ status, isUrdu }) => {
  const styles: Record<string, string> = {
    paid: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300',
    pending: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
    partial: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',
    overdue: 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300',
    active: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300',
    completed: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',
    inactive: 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-300',
    sale: 'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300',
    installment: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',
    advance: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
    recovery: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300',
  };
  const labels: Record<string, string> = {
    paid: isUrdu ? 'ادا' : 'Paid',
    pending: isUrdu ? 'زیر التواء' : 'Pending',
    partial: isUrdu ? 'جزوی' : 'Partial',
    overdue: isUrdu ? 'تاخیر شدہ' : 'Overdue',
    active: isUrdu ? 'فعال' : 'Active',
    completed: isUrdu ? 'مکمل' : 'Completed',
    inactive: isUrdu ? 'غیر فعال' : 'Inactive',
    sale: isUrdu ? 'فروخت' : 'Sale',
    installment: isUrdu ? 'قسط' : 'Installment',
    advance: isUrdu ? 'ایڈوانس' : 'Advance',
    recovery: isUrdu ? 'وصولی' : 'Recovery',
  };
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold ${styles[status] || styles.inactive}`}>
      {labels[status] || status}
    </span>
  );
};

// ==================== SUMMARY CARDS ====================
const ReportSummaryCards: React.FC<{ 
  data: DailyReportData; 
  isUrdu: boolean;
  type: string;
}> = ({ data, isUrdu, type }) => {
  const typeLabels: Record<string, string> = {
    daily: isUrdu ? 'یومیہ' : 'Daily',
    weekly: isUrdu ? 'ہفتہ وار' : 'Weekly',
    monthly: isUrdu ? 'ماہانہ' : 'Monthly',
    'date-range': isUrdu ? 'تاریخ سے تاریخ' : 'Date to Date',
  };

  // Safe number formatter - handles undefined/null values
  const fmt = (val: any): string => {
    const num = Number(val);
    return isNaN(num) ? '0' : num.toLocaleString();
  };

  return (
    <>
      {/* Header Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
        <div className="bg-gradient-to-br from-blue-50 to-blue-100 dark:from-blue-900/20 dark:to-blue-900/30 rounded-xl p-3 border border-blue-200 dark:border-blue-800">
          <p className="text-xs font-semibold text-blue-600 dark:text-blue-400">{isUrdu ? 'کل فروخت' : 'Total Sales'}</p>
          <p className="text-xl font-extrabold text-blue-800 dark:text-blue-200">Rs. {fmt(data.totalSales)}</p>
          <p className="text-[10px] text-blue-500 dark:text-blue-400">{data.totalCustomers || 0} {isUrdu ? 'گاہک' : 'Customers'}</p>
        </div>
        <div className="bg-gradient-to-br from-emerald-50 to-emerald-100 dark:from-emerald-900/20 dark:to-emerald-900/30 rounded-xl p-3 border border-emerald-200 dark:border-emerald-800">
          <p className="text-xs font-semibold text-emerald-600 dark:text-emerald-400">{isUrdu ? 'وصول شدہ' : 'Collected'}</p>
          <p className="text-xl font-extrabold text-emerald-800 dark:text-emerald-200">Rs. {fmt(data.totalCollected)}</p>
          <p className="text-[10px] text-emerald-500 dark:text-emerald-400">{data.totalInstallments || 0} {isUrdu ? 'اقساط' : 'Installments'}</p>
        </div>
        <div className="bg-gradient-to-br from-amber-50 to-amber-100 dark:from-amber-900/20 dark:to-amber-900/30 rounded-xl p-3 border border-amber-200 dark:border-amber-800">
          <p className="text-xs font-semibold text-amber-600 dark:text-amber-400">{isUrdu ? 'زیر التواء' : 'Pending'}</p>
          <p className="text-xl font-extrabold text-amber-800 dark:text-amber-200">Rs. {fmt(data.totalPending)}</p>
          <p className="text-[10px] text-amber-500 dark:text-amber-400">{data.recoveryRate || 0}% {isUrdu ? 'وصولی کی شرح' : 'Recovery Rate'}</p>
        </div>
        <div className="bg-gradient-to-br from-purple-50 to-purple-100 dark:from-purple-900/20 dark:to-purple-900/30 rounded-xl p-3 border border-purple-200 dark:border-purple-800">
          <p className="text-xs font-semibold text-purple-600 dark:text-purple-400">{isUrdu ? 'نقد ہاتھ' : 'Cash in Hand'}</p>
          <p className="text-xl font-extrabold text-purple-800 dark:text-purple-200">Rs. {fmt(data.cashInHand)}</p>
          <p className="text-[10px] text-purple-500 dark:text-purple-400">{isUrdu ? 'بینک جمع' : 'Bank Deposit'}: Rs. {fmt(data.bankDeposit)}</p>
        </div>
      </div>

      {/* Account Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
        <div className="bg-gradient-to-br from-cyan-50 to-cyan-100 dark:from-cyan-900/20 dark:to-cyan-900/30 rounded-xl p-3 border border-cyan-200 dark:border-cyan-800">
          <p className="text-xs font-semibold text-cyan-600 dark:text-cyan-400">{isUrdu ? 'کھلے اکاؤنٹس' : 'Open Accounts'}</p>
          <p className="text-lg font-extrabold text-cyan-800 dark:text-cyan-200">{data.openAccounts || 0}</p>
        </div>
        <div className="bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900/20 dark:to-gray-900/30 rounded-xl p-3 border border-gray-200 dark:border-gray-800">
          <p className="text-xs font-semibold text-gray-600 dark:text-gray-400">{isUrdu ? 'بند اکاؤنٹس' : 'Closed Accounts'}</p>
          <p className="text-lg font-extrabold text-gray-800 dark:text-gray-200">{data.closedAccounts || 0}</p>
        </div>
        <div className="bg-gradient-to-br from-indigo-50 to-indigo-100 dark:from-indigo-900/20 dark:to-indigo-900/30 rounded-xl p-3 border border-indigo-200 dark:border-indigo-800">
          <p className="text-xs font-semibold text-indigo-600 dark:text-indigo-400">{isUrdu ? 'خالص اکاؤنٹس' : 'Net Accounts'}</p>
          <p className="text-lg font-extrabold text-indigo-800 dark:text-indigo-200">{data.netAccounts || 0}</p>
        </div>
        <div className="bg-gradient-to-br from-rose-50 to-rose-100 dark:from-rose-900/20 dark:to-rose-900/30 rounded-xl p-3 border border-rose-200 dark:border-rose-800">
          <p className="text-xs font-semibold text-rose-600 dark:text-rose-400">{isUrdu ? 'کل بقایا' : 'Total Outstanding'}</p>
          <p className="text-lg font-extrabold text-rose-800 dark:text-rose-200">Rs. {fmt(data.totalOutstanding)}</p>
        </div>
      </div>

      {/* Breakdown Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-4">
        <div className="bg-white dark:bg-gray-800 rounded-lg p-2 border border-gray-200 dark:border-gray-700 text-center">
          <p className="text-[10px] font-semibold text-gray-500 dark:text-gray-400">{isUrdu ? 'نقد فروخت' : 'Cash Sales'}</p>
          <p className="text-sm font-bold text-gray-800 dark:text-gray-200">Rs. {fmt(data.cashSales)}</p>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-lg p-2 border border-gray-200 dark:border-gray-700 text-center">
          <p className="text-[10px] font-semibold text-gray-500 dark:text-gray-400">{isUrdu ? 'قسط فروخت' : 'Installment Sales'}</p>
          <p className="text-sm font-bold text-gray-800 dark:text-gray-200">Rs. {fmt(data.installmentSales)}</p>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-lg p-2 border border-gray-200 dark:border-gray-700 text-center">
          <p className="text-[10px] font-semibold text-gray-500 dark:text-gray-400">{isUrdu ? 'قسط وصولی' : 'Inst. Collections'}</p>
          <p className="text-sm font-bold text-gray-800 dark:text-gray-200">Rs. {fmt(data.installmentCollections)}</p>
        </div>
        <div className="bg-white dark:bg-gray-800 rounded-lg p-2 border border-gray-200 dark:border-gray-700 text-center">
          <p className="text-[10px] font-semibold text-gray-500 dark:text-gray-400">{isUrdu ? 'ایڈوانس' : 'Advance Payments'}</p>
          <p className="text-sm font-bold text-gray-800 dark:text-gray-200">Rs. {fmt(data.advancePayments)}</p>
        </div>
      </div>
    </>
  );
};

// ==================== MAIN REPORT TABLE ====================
const TransactionTable: React.FC<{
  transactions: DailyReportData['transactions'];
  isUrdu: boolean;
  type: string;
}> = ({ transactions, isUrdu, type }) => {
  if (transactions.length === 0) {
    return (
      <div className="text-center py-8 text-gray-500 dark:text-gray-400">
        {isUrdu ? 'کوئی ٹرانزیکشن نہیں' : 'No transactions found'}
      </div>
    );
  }

  return (
    <>
      {/* ✅ Mobile Card View */}
      <div className="sm:hidden space-y-3">
        {transactions.map((t, idx) => (
          <div key={t.id} className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-3 space-y-2 shadow-sm">
            <div className="flex items-start justify-between">
              <div>
                <p className="font-semibold text-gray-800 dark:text-white text-sm">
                  {isUrdu ? t.customerUrdu || t.customerName : t.customerName}
                </p>
                {t.fatherName && <p className="text-xs text-gray-500 dark:text-gray-400">{t.fatherName}</p>}
              </div>
              <div className="flex flex-col items-end gap-1">
                <StatusBadge status={t.type} isUrdu={isUrdu} />
                <StatusBadge status={t.status} isUrdu={isUrdu} />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-1.5 text-xs">
              <div><span className="text-gray-500 dark:text-gray-400">{isUrdu ? 'فون' : 'Phone'}:</span> <span className="font-mono">{t.phone || '—'}</span></div>
              <div><span className="text-gray-500 dark:text-gray-400">{isUrdu ? 'پروڈکٹ' : 'Product'}:</span> <span>{isUrdu ? t.productNameUrdu || t.productName : t.productName}</span></div>
              <div className="col-span-2"><span className="text-gray-500 dark:text-gray-400">{isUrdu ? 'رقم' : 'Amount'}:</span> <span className="font-semibold">Rs. {t.amount.toLocaleString()}</span></div>
              <div className="col-span-2"><span className="text-gray-500 dark:text-gray-400">{isUrdu ? 'تاریخ' : 'Date'}:</span> <span>{t.date ? new Date(t.date).toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK') : '—'}</span></div>
            </div>
          </div>
        ))}
      </div>
      {/* ✅ Desktop Table View */}
      <div className="hidden sm:block overflow-x-auto">
        <table className="w-full min-w-[900px] text-sm border-collapse">
          <thead>
            <tr className="bg-gradient-to-r from-blue-600 to-blue-700 text-white">
              <th className="px-3 py-2.5 text-start text-xs font-bold uppercase tracking-wider border border-blue-800">
                {isUrdu ? 'گاہک کا نام' : 'Customer Name'}
              </th>
              <th className="px-3 py-2.5 text-start text-xs font-bold uppercase tracking-wider border border-blue-800">
                {isUrdu ? 'والد کا نام' : 'Father Name'}
              </th>
              <th className="px-3 py-2.5 text-start text-xs font-bold uppercase tracking-wider border border-blue-800">
                {isUrdu ? 'فون' : 'Phone'}
              </th>
              <th className="px-3 py-2.5 text-start text-xs font-bold uppercase tracking-wider border border-blue-800">
                {isUrdu ? 'پروڈکٹ' : 'Product'}
              </th>
              <th className="px-3 py-2.5 text-center text-xs font-bold uppercase tracking-wider border border-blue-800">
                {isUrdu ? 'قسم' : 'Type'}
              </th>
              <th className="px-3 py-2.5 text-end text-xs font-bold uppercase tracking-wider border border-blue-800">
                {isUrdu ? 'رقم' : 'Amount'}
              </th>
              <th className="px-3 py-2.5 text-center text-xs font-bold uppercase tracking-wider border border-blue-800">
                {isUrdu ? 'حالت' : 'Status'}
              </th>
              <th className="px-3 py-2.5 text-center text-xs font-bold uppercase tracking-wider border border-blue-800">
                {isUrdu ? 'تاریخ' : 'Date'}
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {transactions.map((t, idx) => (
              <tr key={t.id} className={`${idx % 2 === 0 ? 'bg-white' : 'bg-gray-50'} hover:bg-blue-50 transition-colors`}>
                <td className="px-3 py-2 font-semibold text-gray-800 border border-gray-200">
                  {isUrdu ? t.customerUrdu || t.customerName : t.customerName}
                </td>
                <td className="px-3 py-2 text-gray-600 border border-gray-200">{t.fatherName || '—'}</td>
                <td className="px-3 py-2 text-gray-600 font-mono text-xs border border-gray-200" dir="ltr">{t.phone || '—'}</td>
                <td className="px-3 py-2 text-gray-600 border border-gray-200">
                  {isUrdu ? t.productNameUrdu || t.productName : t.productName}
                </td>
                <td className="px-3 py-2 text-center border border-gray-200">
                  <StatusBadge status={t.type} isUrdu={isUrdu} />
                </td>
                <td className="px-3 py-2 text-end font-semibold border border-gray-200">
                  Rs. {t.amount.toLocaleString()}
                </td>
                <td className="px-3 py-2 text-center border border-gray-200">
                  <StatusBadge status={t.status} isUrdu={isUrdu} />
                </td>
                <td className="px-3 py-2 text-center font-mono text-xs border border-gray-200">
                  {t.date ? new Date(t.date).toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK') : '—'}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
};

// ==================== MAIN COMPONENT ====================
const CustomerReport: React.FC = () => {
  const { t, i18n } = useTranslation();
  const isUrdu = i18n.language === 'ur';

  const [reportType, setReportType] = useState<'daily' | 'weekly' | 'monthly' | 'date-range'>('daily');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [reportData, setReportData] = useState<DailyReportData | null>(null);
  const [search, setSearch] = useState('');
  const reportRef = useRef<HTMLDivElement>(null);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  // Set default dates
  useEffect(() => {
    const today = new Date();
    const weekAgo = new Date(today);
    weekAgo.setDate(today.getDate() - 7);
    const monthAgo = new Date(today);
    monthAgo.setMonth(today.getMonth() - 1);
    
    setStartDate(today.toISOString().split('T')[0]);
    setEndDate(today.toISOString().split('T')[0]);
  }, []);

  // ==================== API CALLS ====================
  const fetchReport = useCallback(async () => {
    setLoading(true);
    setError('');
    setReportData(null);

    try {
      const today = new Date();
      const todayStr = today.toISOString().split('T')[0];

      // Build query params based on report type
      let params: Record<string, string> = {};
      let endpoint = '';
      let weekAgo: Date;
      let monthAgo: Date;
      
      switch (reportType) {
        case 'daily':
          endpoint = '/reports/daily';
          params = { date: todayStr };
          break;
        case 'weekly':
          endpoint = '/reports/weekly';
          weekAgo = new Date(today);
          weekAgo.setDate(today.getDate() - 7);
          params = { startDate: weekAgo.toISOString().split('T')[0], endDate: todayStr };
          break;
        case 'monthly':
          endpoint = '/reports/monthly';
          monthAgo = new Date(today);
          monthAgo.setMonth(today.getMonth() - 1);
          params = { startDate: monthAgo.toISOString().split('T')[0], endDate: todayStr };
          break;
        case 'date-range':
          endpoint = '/reports/date-range';
          if (!startDate || !endDate) {
            setError(isUrdu ? 'تاریخ کی حد منتخب کریں' : 'Please select date range');
            setLoading(false);
            return;
          }
          params = { startDate, endDate };
          break;
      }

      // Call the real API endpoint
      const res = await api.get(endpoint, { params });
      const response = res.data;

      setReportData(response);
      toast.success(isUrdu ? 'رپورٹ تیار ہو گئی' : 'Report generated successfully');

    } catch (err: any) {
      console.error('Report fetch error:', err);
      // If API fails, use mock data for demo
      try {
        const mockData = await generateMockReport(reportType, { 
          startDate: startDate || new Date().toISOString().split('T')[0], 
          endDate: endDate || new Date().toISOString().split('T')[0] 
        });
        setReportData(mockData);
        toast.success(isUrdu ? 'مثال رپورٹ تیار ہو گئی' : 'Sample report generated');
      } catch {
        setError(isUrdu ? 'رپورٹ بنانے میں ناکامی' : 'Failed to generate report');
        toast.error(isUrdu ? 'رپورٹ نہیں بن سکی' : 'Report generation failed');
      }
    } finally {
      setLoading(false);
    }
  }, [reportType, startDate, endDate, isUrdu]);

  // ==================== MOCK DATA GENERATOR (Fallback) ====================
  const generateMockReport = async (type: string, params: Record<string, string>): Promise<DailyReportData> => {
    await new Promise(resolve => setTimeout(resolve, 500));

    const today = new Date();
    const start = params.startDate ? new Date(params.startDate) : today;
    const end = params.endDate ? new Date(params.endDate) : today;

    const random = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;
    const totalSales = random(50000, 200000);
    const totalCollected = random(30000, 150000);
    const totalPending = totalSales - totalCollected;
    const totalInstallments = random(5, 30);
    const totalCustomers = random(2, 15);
    const cashInHand = random(20000, 100000);
    const bankDeposit = random(10000, 50000);
    const recoveryRate = Math.round((totalCollected / totalSales) * 100);

    const names = ['M Nazir', 'Ahmed Khan', 'Sadia Batool', 'Usman Ali', 'Fatima Noor', 'Ali Raza', 'Hina Khan'];
    const urduNames = ['محمد نذیر', 'احمد خان', 'سعدیہ بتول', 'عثمان علی', 'فاطمہ نور', 'علی رضا', 'حنا خان'];
    const fatherNames = ['Muhammad Iqbal', 'Abdul Rehman', 'Muhammad Yousaf', 'Saeed Ahmed', 'Muhammad Ali'];
    const products = ['Mobile Phones', 'Refrigerator', 'LED TV', 'Washing Machine', 'Laptop', 'Air Conditioner'];
    const urduProducts = ['موبائل فون', 'ریفریجریٹر', 'ایل ای ڈی ٹی وی', 'واشنگ مشین', 'لیپ ٹاپ', 'ایئر کنڈیشنر'];
    const types = ['sale', 'installment', 'advance', 'recovery'] as const;
    const statuses = ['paid', 'pending', 'partial'] as const;

    const transactions = Array.from({ length: random(5, 20) }, (_, i) => {
      const idx = random(0, names.length - 1);
      const date = new Date(start);
      date.setDate(date.getDate() + random(0, Math.max(0, Math.floor((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)))));
      return {
        id: `txn-${Date.now()}-${i}`,
        customerName: names[idx % names.length],
        customerUrdu: urduNames[idx % urduNames.length],
        fatherName: fatherNames[random(0, fatherNames.length - 1)],
        phone: `03${random(0, 9)}${random(0, 9)}${random(0, 9)}${random(0, 9)}${random(0, 9)}${random(0, 9)}${random(0, 9)}`,
        productName: products[random(0, products.length - 1)],
        productNameUrdu: urduProducts[random(0, urduProducts.length - 1)],
        amount: random(1000, 15000),
        type: types[random(0, types.length - 1)],
        status: statuses[random(0, statuses.length - 1)],
        date: date.toISOString().split('T')[0],
      };
    });

    return {
      date: today.toISOString().split('T')[0],
      dayName: today.toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK', { weekday: 'long' }),
      totalSales, totalInstallments, totalCollected, totalPending, totalCustomers,
      cashInHand, bankDeposit, recoveryRate, outstanding: totalPending,
      transactions,
      cashSales: random(10000, 50000), cashSalesReturn: random(0, 5000),
      installmentSales: random(30000, 100000), installmentCollections: random(20000, 80000),
      advancePayments: random(5000, 20000), fineReceived: random(0, 5000), processingFee: random(0, 3000),
      openAccounts: random(100, 300), closedAccounts: random(50, 150), netAccounts: random(50, 200),
      freshOutstanding: random(10000, 50000), regularOutstanding: random(50000, 150000),
      totalOutstanding: random(60000, 200000),
    };
  };

  // ==================== HANDLERS ====================
  const handleGenerate = useCallback(() => {
    fetchReport();
  }, [fetchReport]);

  const downloadPDF = useCallback(async () => {
    if (!reportRef.current || !reportData) return;
    setIsGeneratingPDF(true);
    const loadingToast = toast.loading(isUrdu ? 'پی ڈی ایف بنا رہے ہیں...' : 'Generating PDF...');
    try {
      const canvas = await html2canvas(reportRef.current, { 
        scale: 2, 
        useCORS: true, 
        logging: false, 
        backgroundColor: '#ffffff', 
        allowTaint: true 
      });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      let heightLeft = pdfHeight;
      let position = 0;
      const pageHeight = pdf.internal.pageSize.getHeight();
      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
      heightLeft -= pageHeight;
      while (heightLeft > 0) {
        position = heightLeft - pdfHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
        heightLeft -= pageHeight;
      }
      const reportNames: Record<string, string> = {
        daily: 'Daily_Report',
        weekly: 'Weekly_Report',
        monthly: 'Monthly_Report',
        'date-range': 'Date_Range_Report'
      };
      pdf.save(`${reportNames[reportType] || 'Report'}_${new Date().toISOString().split('T')[0]}.pdf`);
      toast.dismiss(loadingToast);
      toast.success(isUrdu ? 'پی ڈی ایف ڈاؤن لوڈ ہو گئی' : 'PDF downloaded successfully');
    } catch (err) {
      toast.dismiss(loadingToast);
      toast.error(isUrdu ? 'پی ڈی ایف بنانے میں ناکامی' : 'PDF generation failed');
    } finally {
      setIsGeneratingPDF(false);
    }
  }, [reportRef, reportData, reportType, isUrdu]);

  // ==================== FILTERING ====================
  const filteredTransactions = useMemo(() => {
    if (!reportData) return [];
    if (!search) return reportData.transactions;
    const q = search.toLowerCase();
    return reportData.transactions.filter(t =>
      t.customerName.toLowerCase().includes(q) ||
      (t.customerUrdu || '').includes(q) ||
      t.phone.includes(q) ||
      t.productName.toLowerCase().includes(q)
    );
  }, [reportData, search]);

  // ==================== RENDER ====================
  const getReportTitle = () => {
    const titles: Record<string, string> = {
      daily: isUrdu ? 'یومیہ رپورٹ' : 'Daily Report',
      weekly: isUrdu ? 'ہفتہ وار رپورٹ' : 'Weekly Report',
      monthly: isUrdu ? 'ماہانہ رپورٹ' : 'Monthly Report',
      'date-range': isUrdu ? 'تاریخ سے تاریخ رپورٹ' : 'Date to Date Report',
    };
    return titles[reportType] || '';
  };

  const getReportSubtitle = () => {
    if (reportType === 'date-range' && startDate && endDate) {
      return `${startDate} ${isUrdu ? 'سے' : 'to'} ${endDate}`;
    }
    if (reportType === 'daily') {
      return new Date().toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      });
    }
    if (reportType === 'weekly') {
      const weekAgo = new Date();
      weekAgo.setDate(weekAgo.getDate() - 7);
      return `${weekAgo.toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK')} ${isUrdu ? 'سے' : 'to'} ${new Date().toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK')}`;
    }
    if (reportType === 'monthly') {
      const monthAgo = new Date();
      monthAgo.setMonth(monthAgo.getMonth() - 1);
      return `${monthAgo.toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK', { month: 'long', year: 'numeric' })} ${isUrdu ? 'سے' : 'to'} ${new Date().toLocaleDateString(isUrdu ? 'ur-PK' : 'en-PK', { month: 'long', year: 'numeric' })}`;
    }
    return undefined;
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-gray-800 dark:text-white">
              {isUrdu ? 'رپورٹس' : 'Reports'}
            </h1>
            <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
              {isUrdu ? 'تمام رپورٹس پرنٹ کریں' : 'Generate and print all reports'}
            </p>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={handleGenerate}
              disabled={loading}
              className="px-5 py-2.5 bg-gradient-to-r from-blue-600 to-blue-700 text-white rounded-xl font-semibold text-sm hover:from-blue-700 hover:to-blue-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg shadow-blue-200 dark:shadow-blue-900/30"
            >
              {loading ? (
                <span className="flex items-center gap-2">
                  <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  {isUrdu ? 'لوڈ ہو رہا ہے...' : 'Loading...'}
                </span>
              ) : (
                <span className="flex items-center gap-2">
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  {isUrdu ? 'رپورٹ بنائیں' : 'Generate Report'}
                </span>
              )}
            </button>
            {reportData && (
              <button
                onClick={downloadPDF}
                disabled={isGeneratingPDF}
                className="px-5 py-2.5 bg-gradient-to-r from-emerald-600 to-emerald-700 text-white rounded-xl font-semibold text-sm hover:from-emerald-700 hover:to-emerald-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg shadow-emerald-200 dark:shadow-emerald-900/30"
              >
                {isGeneratingPDF ? (
                  <span className="flex items-center gap-2">
                    <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    {isUrdu ? 'پی ڈی ایف...' : 'PDF...'}
                  </span>
                ) : (
                  <span className="flex items-center gap-2">
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    {isUrdu ? 'پی ڈی ایف ڈاؤن لوڈ' : 'Download PDF'}
                  </span>
                )}
              </button>
            )}
          </div>
        </div>

        {/* Report Type Selector */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-700 p-4 sm:p-6 mb-6">
          <div className="flex flex-wrap gap-2">
            {(['daily', 'weekly', 'monthly', 'date-range'] as const).map((type) => {
              const labels: Record<string, string> = {
                daily: isUrdu ? 'یومیہ' : 'Daily',
                weekly: isUrdu ? 'ہفتہ وار' : 'Weekly',
                monthly: isUrdu ? 'ماہانہ' : 'Monthly',
                'date-range': isUrdu ? 'تاریخ سے تاریخ' : 'Date to Date',
              };
              const icons: Record<string, string> = {
                daily: '📅',
                weekly: '📆',
                monthly: '📊',
                'date-range': '📋',
              };
              return (
                <button
                  key={type}
                  onClick={() => setReportType(type)}
                  className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold transition-all ${
                    reportType === type
                      ? 'bg-blue-600 text-white shadow-lg shadow-blue-200 dark:shadow-blue-900/30'
                      : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
                  }`}
                >
                  <span>{icons[type]}</span>
                  <span>{labels[type]}</span>
                </button>
              );
            })}
          </div>

          {/* Date Range Picker */}
          {reportType === 'date-range' && (
            <div className="flex flex-wrap items-center gap-3 mt-4 p-4 bg-gray-50 dark:bg-gray-900/50 rounded-xl">
              <div>
                <label className="block text-xs font-semibold text-gray-500 dark:text-gray-400 mb-1">
                  {isUrdu ? 'تاریخ سے' : 'From Date'}
                </label>
                <input
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                  className="px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label className="block text-xs font-semibold text-gray-500 dark:text-gray-400 mb-1">
                  {isUrdu ? 'تاریخ تک' : 'To Date'}
                </label>
                <input
                  type="date"
                  value={endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                  className="px-3 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
            </div>
          )}

          {/* Search */}
          {reportData && reportData.transactions.length > 0 && (
            <div className="mt-4">
              <input
                type="text"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder={isUrdu ? 'تلاش کریں...' : 'Search...'}
                className="w-full px-4 py-2.5 rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
          )}
        </div>

        {/* Error */}
        {error && (
          <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-2xl p-4 mb-6">
            <p className="text-red-700 dark:text-red-300 text-sm font-medium">{error}</p>
          </div>
        )}

        {/* Report Content */}
        {reportData && (
          <div
            ref={reportRef}
            className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-700 p-4 sm:p-6 overflow-hidden"
          >
            <ReportHeader 
              title={getReportTitle()} 
              subtitle={getReportSubtitle()} 
              isUrdu={isUrdu}
              reportDate={reportData.date}
            />
            <ReportSummaryCards data={reportData} isUrdu={isUrdu} type={reportType} />
            <TransactionTable 
              transactions={filteredTransactions} 
              isUrdu={isUrdu} 
              type={reportType} 
            />
            <ReportFooter isUrdu={isUrdu} />
          </div>
        )}

        {/* Empty State */}
        {!reportData && !loading && !error && (
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-700 p-12 text-center">
            <div className="text-6xl mb-4">📄</div>
            <h3 className="text-lg font-semibold text-gray-700 dark:text-gray-300 mb-2">
              {isUrdu ? 'کوئی رپورٹ نہیں' : 'No Report Generated'}
            </h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 max-w-md mx-auto">
              {isUrdu
                ? 'رپورٹ کی قسم منتخب کریں اور "رپورٹ بنائیں" بٹن پر کلک کریں'
                : 'Select a report type and click "Generate Report" button'}
            </p>
          </div>
        )}

        {/* Loading State */}
        {loading && (
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-700 p-12 text-center">
            <div className="animate-spin text-4xl mb-4">⏳</div>
            <h3 className="text-lg font-semibold text-gray-700 dark:text-gray-300">
              {isUrdu ? 'رپورٹ تیار ہو رہی ہے...' : 'Generating report...'}
            </h3>
          </div>
        )}
      </div>
    </div>
  );
};

export default CustomerReport;